### ISSUE TITLE
[code review] be like water

### ISSUE THREAD

**Issue by ferantivero** [sebasmonia/pyquebec#7]
it doesn't feel like something so pythonish at some point. It is quite a bit statically typed, IMO.

**Comment by sebasmonia** [comment]
Any specific examples? So I can figure out what direction you want to go.

**Comment by ferantivero** [comment]
I think we could ask for attrs instead of types. At some point it ask you for a particular type (e.g Table), it happened to me while mocking.

**Comment by sebasmonia** [comment]
Ok, after thinking a bit about this...I think I created this problem in the first place. A very old version of this concatenated string pieces and when I added objects, I made their **str** return the text that goes in the query:

```
query_text = "SELECT * FROM " + str(a_param)
```

If `a_param` is a string, it keeps working, and now it supports a table. 

It doesn't make sense to keep that, since with the current QueryBuilder you always keep references to the actual objects.

Proposal: tables and columns should have a common interface, by implementing _query_repr() that returns the "query representation" of the object.
Another option could be "_SQL_repr()".

**repr** and **str** could return _query_repr() + databasename
Example:

```
>>> myObj.dbo.Employee
Table "dbo.Employee" in database "Payroll"
>>> str(myObj.dbo.Employee)
Table "dbo.Employee" in database "Payroll"
```

**Comment by ferantivero** [comment]
You are in the correct path. But it wasn't exactly the same issue I faced.

There is a piece of code that expects an object to be a Table type and nothing else...

**Comment by sebasmonia** [comment]
Yep, all code that validates the parameters is checking for Table, Column, etc. 
For example, `From(param1)` will check the type: if it's a table, use it, if it's a string, search for the table, if it's a list of tablets, etc. 

I will change it to check if the object has a  `_query_repr` attribute.
- Cons: only I can think of is that if someone uses a column in a `From()` or a table in an `order_by` it will not fail
- Pros: not tied to the type, can add more objects later easily (I don't know, call to procs, etc.)

**Comment by sebasmonia** [comment]
Change is merged and tested a bit.

As a consequence dbobject doesn't need the import of Table and Column, so QueryBuilder can be tested by using any mock that has a _query_repr() method. The method should return a string that will be added to the query in the corresponding position.

This also allows using a different dbobject" module for other DBs, for example.

**Comment by ferantivero** [comment]
awesome!!!
